/**
 * Re-exports wallet command handlers from the commands folder for wallet-dispatch.
 */
export {
  handleChangeVaultPassword,
  handleCreateVault,
  handleGetState,
  handleLock,
  handleReadIntegrationSecrets,
  handleUnlock,
  handleAddReadOnlyAccount,
  handleDeleteAccount,
  handleExportAccountSecret,
  handleGenerateAccount,
  handleGenerateSeedAccount,
  handleImportAccount,
  handleImportSeedAccount,
  handlePreviewSeedAccounts,
  handleReorderAccounts,
  handleRenameAccount,
  handleSetActiveAccount,
  handleAddCombinedSub,
  handleCreateCombinedAccount,
  handleRemoveCombinedSub,
  handleSetCombinedMain,
  handleDisconnectAllOrigins,
  handleDisconnectOrigin,
  handleBeginSend,
  handlePatchSettings,
} from "./commands";
